### ISSUE TITLE
File structure for module/resolvers..

### ISSUE THREAD

**Issue by smooJitter** [RedLeap/GraphQL#10]
Currently the module/resolvers looks like this,

module/
---resolvers/
------index.js

Does it seem like it would make sense to something along the line of,

module/
---resolvers/
------index.js
------mutations.js
------queries.js
 
where,

`modules/moduleName/resolvers/mutations.js`

```javascript
export default ( ) => ({
     mutation1 ( _, args, context) { ... },
     mutation2 ( _, args, context) { ... },
})
```

`modules/moduleName/resolvers/queries.js`

```javascript
export default ( ) => ({
     query1 ( _, args, context) { ... },
     query2 ( _, args, context) { ... },
})

```
`modules/moduleName/resolvers/index.js`

```javascript 
import mutations from './mutations';
import queries from './queries';

export const resolvers =  ( ) => {
      ... mutations,
      ... queries,
      
     Type1: {
         field1 ( _, args, context) { ... },
         field2 ( _, args, context) { ... },
      },

     Type2: {
         field1 ( _, args, context) { ... },
         field2 ( _, args, context) { ... },
      },
}
```

**Comment by jakelacey2012** [comment]
I like this idea, if you want to add this to the documentation I all for it :)

**Comment by jakelacey2012** [comment]
Just having another look, somethings will need to be updated to neatly achieve this,

Stuff like in the 
 -  in `core/lib/merge.js` I create & merge `query`, `mutation`, `subscription` this will need to be pluralized .

I'll create a PR for that...

**Comment by jakelacey2012** [comment]
`mutations.js` &  `queryies` can just export objects rather than functions.

**Comment by jakelacey2012** [comment]
I've added this going to close the issue.
