### ISSUE TITLE
Models & Connectors

### ISSUE THREAD

**Issue by smooJitter** [RedLeap/GraphQL#9]
Is in possible to demonstrate the use of models and connectors.  The documentation begins to explain, however, it would be nice to see a simple illustration.

**Comment by jakelacey2012** [comment]
Thanks for getting in touch, yes the documentation is a bit weak there.

I'm going to continue using the example of `Accounts` module,
 
`Accounts` connects to a `MYSQL` database, for that I'm gonna use [sequelize.js](http://docs.sequelizejs.com/en/v3/)

`modules/accounts/modules/connector.js`
```javascript

// This is not a complete example
export const accountsDB = new Sequelize('database', 'username', 'password', {
  host: 'localhost',
  dialect: 'mysql',
});

```

`modules/accounts/modules/accounts.model.js`
```javascript
import { accountsDB } from './connector.js'

var Project = accountsDB.define(accounts,  {
  firstname: Sequelize.STRING,
  lastname: Sequelize.STRING
})

```

`modules/accounts/modules/index.js`
```javascript
import './accounts.model.js';
import { accountsDB } from './sequelize';

// Here you want to export your models,
export const models = () => {
   return {
      accountModels: accountsDB,
   } 
}

```

What I've tried to achieve here is that we export all of the models from `index.js`, sequelizes confuses this slighted my making both the connector and the model the same object.

I hope that helps let me know if you have any questions :)

**Comment by smooJitter** [comment]
Two questions:

1). Should this 

`modules/accounts/modules/...`

become this,

`modules/accounts/models/...`

2). Is this how the models are exposed?

`modules/accounts/index.js`
```
export * from './schema'
export * from './resolvers'
export * from './models'
```

Thanks for the quick response.

**Comment by jakelacey2012** [comment]
1) Yes that was a typo sorry,

2) models are exposed like this, like your first example
`modules/accounts/index.js`
```
export * from './schema'
export * from './resolvers'
export * from './models'
```

I've tried to abstract away the connector, if that makes sense but if you can think of a reason I need to expose that too let me know.

**Comment by jakelacey2012** [comment]
I'm going to close this issue now, let me know if you have any more questions :)
